"""L6 · 反思演进（Reflection Loop）——[08](../../../docs/技术架构-v2/08-L6-反思演进.md)。

本层首批（[T-L6-001](../../../项目管理/tasks/T-L6-001-反馈采集FeedbackEvent每周反思报告.md)）交付
[08 §1–§2](../../../docs/技术架构-v2/08-L6-反思演进.md)：**反思数据池**（反馈落 `reflection`
分区、本机不外发）与**每周反思报告**（四段式 · 完整 Trace · 两处空态 · 经 L5 渠道分发）。
第二批（[T-L6-002](../../../项目管理/tasks/T-L6-002-训练对话协议主动提案与AB实验.md)）交付
[08 §3–§4](../../../docs/技术架构-v2/08-L6-反思演进.md)：**训练对话协议**（概念性理解 · 确认门 ·
记忆 `pattern` 写入 · 提案候选 · 回访留痕）、**主动提案**（模式识别 · Skill 草稿 · 频率上限 ·
周报第四段候选生成）与 **A/B 实验**（五字段 · 留痕 · 保守判定 · 授权面预留）。
第三批（[T-L6-003](../../../项目管理/tasks/T-L6-003-演进授权与变更流回滚与出厂重置.md)）交付
[08 §5–§7](../../../docs/技术架构-v2/08-L6-反思演进.md)：**演进授权档位与风险分级清单**
（三档 · 切换留痕 · 实验授权面的实体）、**变更流与单项回滚**（提案 → 审批门 → 生效 → 告知 ·
变更历史 · 一键回滚）与**出厂重置**（三次确认 · 演进状态清空 · Memory 保留）。
M5 批（[T-AGT-005.1](../../../项目管理/tasks/T-AGT-005.1-运行期授权档位与共享清单.md)）在
[08 §5](../../../docs/技术架构-v2/08-L6-反思演进.md) 的共享口径下补**运行期授权档位**
（`agent.authorization`，独立条目）与判据面——**清单仍只此一份**（`evolution.risk-grading`），
运行期侧只是消费方。

三个面各自独立可用，由 [`runtime.build_l6`](runtime.py) 接成一层；跨层组合根归关卡
[T-INT-005](../../../项目管理/tasks/T-INT-005-M4集成关卡反思演进与生态闭环.md)。

**只向下依赖**（[铁律 7](../../../项目管理/工程宪法.md)）：本层消费 L0 的 `reflection` 分区、
[01 §11](../../../docs/技术架构-v2/01-平台共享契约.md) 的事件面、[01 §7](../../../docs/技术架构-v2/01-平台共享契约.md)
的配置门面、L2 的记忆读取面、L3 的反馈事件模型与 L5 的投递 / 渠道面——**不反向**。
"""

from __future__ import annotations

from st_agent.l6.authorization import (
    DEFAULT_RISK_GRADING,
    DEFAULT_SCOPES,
    DEFAULT_TIER,
    GRADING_CONFIG_ID,
    RISK_CLASSES,
    TIER_CONFIG_ID,
    TIERS,
    EvolutionAuthorization,
    EvolutionRiskRule,
    PermitDecision,
    RiskClass,
    Tier,
)
from st_agent.l6.authorization_store import (
    CHANGE_PREFIX as AUTHORIZATION_CHANGE_PREFIX,
    CONFIG_PREFIX as AUTHORIZATION_CONFIG_PREFIX,
    EvolutionStore,
)
from st_agent.l6.change import (
    CHANGE_APPLIED,
    CHANGE_ROLLED_BACK,
    NO_AUTHORIZATION_REASON,
    NO_REGISTRY_REASON,
    ChangeProposal,
    ChangeRun,
    EvolutionChange,
    EvolutionChangeFlow,
    GateDecision,
    PendingChange,
)
from st_agent.l6.change_store import (
    PENDING_PREFIX,
    RESET_PREFIX,
    EvolutionChangeStore,
)
from st_agent.l6.change_store import CHANGE_PREFIX as EVOLUTION_CHANGE_PREFIX
from st_agent.l6.experiment import (
    AUTHORIZER_ABSENT_REASON,
    DEFAULT_MIN_SAMPLE,
    LOW_RISK_SCOPES,
    NOT_PERMITTED_REASON,
    STOP_REASON,
    Experiment,
    ExperimentConsole,
    ExperimentStart,
    judge,
)
from st_agent.l6.experiment_store import EXPERIMENT_PREFIX, ExperimentStore
from st_agent.l6.errors import (
    AuthorizationError,
    ChangeFlowError,
    ExperimentError,
    FactoryResetError,
    FeedbackPoolError,
    L6Error,
    ProposalError,
    TrainingError,
    WeeklyReportError,
)
from st_agent.l6.pool import (
    FEEDBACK_EVENT,
    SOURCE,
    FeedbackEntry,
    FeedbackPool,
    PoolCounts,
)
from st_agent.l6.pool_store import FEEDBACK_PREFIX, FeedbackPoolStore
from st_agent.l6.proposal import (
    DEFAULT_RATE_LIMIT,
    DEFAULT_REPEAT_THRESHOLD,
    DEFAULT_RULES,
    NOT_HIT_NOTE,
    OBSERVER_ABSENT_REASON,
    DetectRun,
    PatternObservation,
    ProposalEngine,
    ProposalRule,
    ProposalRun,
    RuleNote,
    SkillDraft,
    SkillProposal,
)
from st_agent.l6.proposal_store import (
    PROPOSAL_PREFIX,
    RATE_LIMIT_CONFIG_ID,
    REPEAT_CONFIG_ID,
    ProposalStore,
)
from st_agent.l6.registry_adapter import (
    GRADING_WRITE_OWNER,
    TEMPLATE_WRITE_OWNER,
    AgentFamily,
    EvolutionFamily,
    ProposalFamily,
    WeeklyReportFamily,
    agent_family,
    evolution_family,
    proposal_family,
    weekly_report_family,
)
from st_agent.l6.reset import (
    REPLAY_NOTE,
    RESET_CONFIRMATIONS,
    FactoryReset,
    ResetOutcome,
)
from st_agent.l6.runtime import L6Stack, build_l6
from st_agent.l6.runtime_authorization import (
    ACTION_VERDICTS,
    AGENT_CHANGE_PREFIX,
    AGENT_CONFIG_PREFIX,
    AGENT_TIER_CONFIG_ID,
    MEMORY_WRITE_ACTION,
    NET_EGRESS_ACTION,
    SKILL_ACTION_PREFIX,
    ActionDecision,
    ActionVerdict,
    RuntimeAuthorization,
    skill_action_id,
)
from st_agent.l6.training import (
    CALLBACK_NOTICE,
    MEMORY_ABSENT_NOTE,
    NO_SUGGESTION_NOTE,
    TRAINING_CONFIDENCE,
    TRAINING_PRIVACY,
    UNDERSTANDER_ABSENT_REASON,
    CallbackNote,
    SuggestionDraft,
    TrainingDraft,
    TrainingOutcome,
    TrainingProtocol,
    TrainingSession,
    TrainingTurn,
)
from st_agent.l6.training_store import TRAINING_PREFIX, TrainingStore
from st_agent.l6.weekly import (
    DEFAULT_CHANNELS,
    DEFAULT_DAY_OF_WEEK,
    DEFAULT_MIN_FEEDBACK,
    DEFAULT_TIME,
    INSUFFICIENT_NOTE,
    NO_ADVISOR_NOTE,
    NO_TOUCH_NOTE,
    SECTION_LABELS,
    WEEK_SECTIONS,
    ProposalCandidate,
    ReportLine,
    ReportSection,
    ReportTemplate,
    ReportTrace,
    WeeklyReport,
    WeeklyReportBuilder,
    due_on,
    week_key,
    week_window,
)
from st_agent.l6.weekly_store import (
    CHANGE_PREFIX,
    CONFIG_PREFIX,
    DAY_CONFIG_ID,
    MIN_FEEDBACK_CONFIG_ID,
    REPORT_PREFIX,
    TEMPLATE_CONFIG_ID,
    TIME_CONFIG_ID,
    WeeklyReportStore,
)

__all__ = [
    "ACTION_VERDICTS",
    "AGENT_CHANGE_PREFIX",
    "AGENT_CONFIG_PREFIX",
    "AGENT_TIER_CONFIG_ID",
    "AUTHORIZATION_CHANGE_PREFIX",
    "AUTHORIZATION_CONFIG_PREFIX",
    "AUTHORIZER_ABSENT_REASON",
    "CALLBACK_NOTICE",
    "CHANGE_APPLIED",
    "CHANGE_PREFIX",
    "CHANGE_ROLLED_BACK",
    "CONFIG_PREFIX",
    "DEFAULT_CHANNELS",
    "DEFAULT_DAY_OF_WEEK",
    "DEFAULT_MIN_FEEDBACK",
    "DEFAULT_MIN_SAMPLE",
    "DEFAULT_RATE_LIMIT",
    "DEFAULT_REPEAT_THRESHOLD",
    "DEFAULT_RISK_GRADING",
    "DEFAULT_RULES",
    "DEFAULT_SCOPES",
    "DEFAULT_TIER",
    "DEFAULT_TIME",
    "DAY_CONFIG_ID",
    "EVOLUTION_CHANGE_PREFIX",
    "EXPERIMENT_PREFIX",
    "FEEDBACK_EVENT",
    "FEEDBACK_PREFIX",
    "GRADING_CONFIG_ID",
    "GRADING_WRITE_OWNER",
    "INSUFFICIENT_NOTE",
    "L6Stack",
    "LOW_RISK_SCOPES",
    "MEMORY_ABSENT_NOTE",
    "MEMORY_WRITE_ACTION",
    "MIN_FEEDBACK_CONFIG_ID",
    "NET_EGRESS_ACTION",
    "NO_ADVISOR_NOTE",
    "NO_AUTHORIZATION_REASON",
    "NO_REGISTRY_REASON",
    "NO_SUGGESTION_NOTE",
    "NO_TOUCH_NOTE",
    "NOT_HIT_NOTE",
    "NOT_PERMITTED_REASON",
    "OBSERVER_ABSENT_REASON",
    "PENDING_PREFIX",
    "PROPOSAL_PREFIX",
    "RATE_LIMIT_CONFIG_ID",
    "REPLAY_NOTE",
    "REPORT_PREFIX",
    "REPEAT_CONFIG_ID",
    "RESET_CONFIRMATIONS",
    "RESET_PREFIX",
    "RISK_CLASSES",
    "SECTION_LABELS",
    "SKILL_ACTION_PREFIX",
    "SOURCE",
    "STOP_REASON",
    "TEMPLATE_CONFIG_ID",
    "TEMPLATE_WRITE_OWNER",
    "TIERS",
    "TIER_CONFIG_ID",
    "TIME_CONFIG_ID",
    "TRAINING_CONFIDENCE",
    "TRAINING_PREFIX",
    "TRAINING_PRIVACY",
    "UNDERSTANDER_ABSENT_REASON",
    "WEEK_SECTIONS",
    "ActionDecision",
    "ActionVerdict",
    "AgentFamily",
    "AuthorizationError",
    "CallbackNote",
    "ChangeFlowError",
    "ChangeProposal",
    "ChangeRun",
    "DetectRun",
    "EvolutionAuthorization",
    "EvolutionChange",
    "EvolutionChangeFlow",
    "EvolutionChangeStore",
    "EvolutionFamily",
    "EvolutionRiskRule",
    "EvolutionStore",
    "Experiment",
    "ExperimentConsole",
    "ExperimentError",
    "ExperimentStart",
    "ExperimentStore",
    "FactoryReset",
    "FactoryResetError",
    "FeedbackEntry",
    "FeedbackPool",
    "FeedbackPoolError",
    "FeedbackPoolStore",
    "GateDecision",
    "L6Error",
    "PatternObservation",
    "PendingChange",
    "PermitDecision",
    "PoolCounts",
    "ProposalCandidate",
    "ProposalEngine",
    "ProposalError",
    "ProposalFamily",
    "ProposalRule",
    "ProposalRun",
    "ProposalStore",
    "ReportLine",
    "ReportSection",
    "ReportTemplate",
    "ReportTrace",
    "ResetOutcome",
    "RiskClass",
    "RuleNote",
    "RuntimeAuthorization",
    "SkillDraft",
    "SkillProposal",
    "SuggestionDraft",
    "Tier",
    "TrainingDraft",
    "TrainingError",
    "TrainingOutcome",
    "TrainingProtocol",
    "TrainingSession",
    "TrainingStore",
    "TrainingTurn",
    "WeeklyReport",
    "WeeklyReportBuilder",
    "WeeklyReportError",
    "WeeklyReportFamily",
    "WeeklyReportStore",
    "agent_family",
    "build_l6",
    "due_on",
    "evolution_family",
    "judge",
    "proposal_family",
    "skill_action_id",
    "week_key",
    "week_window",
    "weekly_report_family",
]
