"""ST Agent · 平台共享契约类型（01-平台共享契约的单一真相源）。

任何层（L0–L6）实现只能 ``from st_agent.contracts import ...``；
各层不得私造跨层格式（技术架构总览 §3.2）。

契约文档：docs/技术架构-v2/01-平台共享契约.md（schema 不锁定序列化格式，
本实现选 JSON 兼容的 pydantic v2 frozen 模型；字段表→模型的映射见各模块 docstring）。
"""

from st_agent.contracts.errors import ContractViolation
from st_agent.contracts.identifiers import (
    FLOW_ID_PATTERN,
    ID_ALIASES,
    ID_KINDS,
    ID_REGISTRY,
    AnnouncementId,
    ChangeId,
    DatasetSnapshotId,
    DeliveryId,
    DescriptionId,
    FeedbackId,
    FlowId,
    LensId,
    MemoryNodeId,
    PlatformId,
    SignalId,
    SkillId,
    SkillRunId,
    StockId,
    TraceId,
    TrialId,
)
from st_agent.contracts.result_envelope import (
    EnvelopeStatus,
    EvidenceRef,
    ResultEnvelope,
)
from st_agent.contracts.schema_check import (
    DIALECT_KEYWORDS,
    SCHEMA_TYPES,
    LinkCheck,
    PayloadCheck,
    SchemaViolation,
    check_link,
    check_payload,
)
from st_agent.contracts.capability_types import (
    LensOpinion,
    ParameterSpec,
    Provenance,
    SkillDescriptor,
)
from st_agent.contracts.permissions import (
    DECISION_LABELS,
    PERMISSION_KINDS,
    PermissionApproval,
    PermissionDecision,
    describe_permission,
)
from st_agent.contracts.neutrality import (
    NeutralityFinding,
    NeutralityGuard,
    NeutralityVerdict,
    default_rulepack,
)
from st_agent.contracts.registry_types import (
    ChangePolicy,
    ChangeRecord,
    ConfigEntry,
    PanelField,
    PermissionAction,
    SemVer,
    VersionBump,
    parse_permission,
    validate_permissions,
)
from st_agent.contracts.time_events import (
    CORE_EVENTS,
    DataAnchor,
    PlatformEvent,
    StalenessVerdict,
)
from st_agent.contracts.trace import (
    STEP_TYPES,
    ConclusionRef,
    Trace,
    TraceError,
    TraceStep,
    digest_of,
)
from st_agent.contracts.ui_description import (
    COMPONENT_TYPES,
    DESCRIPTION_ID_PREFIX,
    IMPLEMENTED_COMPONENT_TYPES,
    RESERVED_COMPONENT_TYPES,
    ComponentType,
    TextKind,
    UiDescription,
    checked_description,
    new_description_id,
)

__all__ = [
    "AnnouncementId",
    "COMPONENT_TYPES",
    "CORE_EVENTS",
    "ChangeId",
    "ChangePolicy",
    "ChangeRecord",
    "ComponentType",
    "ConclusionRef",
    "ConfigEntry",
    "ContractViolation",
    "DESCRIPTION_ID_PREFIX",
    "DataAnchor",
    "DatasetSnapshotId",
    "DECISION_LABELS",
    "DeliveryId",
    "DescriptionId",
    "DIALECT_KEYWORDS",
    "EnvelopeStatus",
    "EvidenceRef",
    "FeedbackId",
    "FLOW_ID_PATTERN",
    "FlowId",
    "ID_ALIASES",
    "ID_KINDS",
    "ID_REGISTRY",
    "IMPLEMENTED_COMPONENT_TYPES",
    "LensId",
    "LensOpinion",
    "LinkCheck",
    "MemoryNodeId",
    "NeutralityFinding",
    "NeutralityGuard",
    "NeutralityVerdict",
    "PanelField",
    "ParameterSpec",
    "PayloadCheck",
    "PERMISSION_KINDS",
    "PermissionAction",
    "PermissionApproval",
    "PermissionDecision",
    "PlatformEvent",
    "PlatformId",
    "Provenance",
    "RESERVED_COMPONENT_TYPES",
    "ResultEnvelope",
    "SCHEMA_TYPES",
    "STEP_TYPES",
    "SchemaViolation",
    "SemVer",
    "SignalId",
    "SkillDescriptor",
    "SkillId",
    "SkillRunId",
    "StalenessVerdict",
    "StockId",
    "TextKind",
    "Trace",
    "TraceError",
    "TraceId",
    "TraceStep",
    "TrialId",
    "UiDescription",
    "VersionBump",
    "check_link",
    "check_payload",
    "checked_description",
    "default_rulepack",
    "describe_permission",
    "digest_of",
    "new_description_id",
    "parse_permission",
    "validate_permissions",
]
