#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""render_ledger.py — ST Agent 任务账本生成器

tasks/*.md 的 YAML frontmatter 是唯一真相源；任务账本.md 是派生视图，勿手改。

子命令：
  bootstrap   一次性：把（手写的）现有账本表格里的行导入为 tasks/T-*.md
              仅创建缺失或带 AUTO 标记的文件；手写文件（无标记）不受影响
  render      扫描 tasks/ 与 tasks/done/ → 重新生成 项目管理/任务账本.md
  archive     把「全部任务 done」的里程碑整批移入 tasks/done/<Mn>/（--dry 预览）
              移动会**改变相对链接的基准**，故同批改正受影响的链接（见 _retarget）
  status      按 children 重算父任务 status 与 depends_on（活跃区）；打印就绪集
              render 走同一派生路径（build_ledger → compute_status），故也会重算

frontmatter 约定：
  文件内部链接（story / arch / 正文）相对 tasks/ → 用 ../../docs/
  arch_link 字段专供账本渲染，相对 项目管理/ → 用 ../docs/
"""
import os, re, shutil, argparse
from datetime import datetime, timezone, timedelta

HERE = os.path.dirname(os.path.abspath(__file__))
PM   = os.path.dirname(HERE)
ROOT = os.path.dirname(PM)
TASKS= os.path.join(PM, "tasks")
DONE = os.path.join(TASKS, "done")
LEDGER = os.path.join(PM, "任务账本.md")
MARK = "<!-- auto-generated by render_ledger bootstrap -->"

ID_RE = re.compile(r"T-(?:SC|UI|L\d|ECO|INT)-\d{3}")
LINK_TGT = re.compile(r'\]\(([^)]+)\)')
MD_LINK = re.compile(r'(\[[^\n]*?\]\()([^)]+)(\))')   # 分组以便只换路径、保链接文字
# ⚠️ 链接文字用**非贪婪** `[^\n]*?` 而非 `[^\]]*`：文字里常出现行内代码携方括号，
# 如 ``[`SkillRunner.run(..., Mapping[str, Any])`](../../src/…)`` —— 用 `[^\]]*`
# 会在 ``Any]`` 处提前收口、与 `](` 失配，整条链接被静默漏改（2026-10-04 归档 M2
# 实测 3 条漏改）。verify_docs 之所以仍报得出，是因为它先 strip_code 去掉行内代码、
# 文字退化为空再匹配；本处要**逐字节保留**原文，故不能照搬那一步。
FENCE = re.compile(r'(```.*?```)', re.S)
SKIP_DIRS = {".git", "__pycache__", "tmp", "temp"}  # 同 verify_docs 的断链扫描口径
NON_REL_PREFIX = ("#", "http", "mailto:", "data:", "tel:")
CST = timezone(timedelta(hours=8))

LAYERS = [
    ("SC",  "SC · 平台共享契约 — Story 平台通用能力",
     "[`10-platform-capabilities`](../docs/PRD-v2-Agent/10-platform-capabilities.md)", "M0"),
    ("L0",  "L0 · 本地优先基座 — Story 5", "[local-first](../docs/PRD-v2-Agent/story-05-local-first.md)", "M0"),
    ("L1",  "L1 · 能力底座 Skills/MCP — Story 2 / 6 / 8",
     "[runtime](../docs/PRD-v2-Agent/story-02-skills-runtime.md) / [studio](../docs/PRD-v2-Agent/story-06-skill-studio.md) / [mcp](../docs/PRD-v2-Agent/story-08-mcp-hub.md)", "M0"),
    ("L2",  "L2 · 记忆图谱 — Story 3", "[memory-graph](../docs/PRD-v2-Agent/story-03-memory-graph.md)", "M1"),
    ("L3",  "L3 · 对话主入口 Chat-as-OS — Story 1", "[chat-as-os](../docs/PRD-v2-Agent/story-01-chat-as-os.md)", "M1"),
    # UI 置于 L3 之后、L4 之前：表现层骨架消费 01 §7 + L1 Studio 首页 + L3 §6 的 UI 描述契约，
    # 依赖止于 L3；它是**跨层工程任务**（同 T-SC-* 先例），**不是第七层**（见 决策日志 D-060）。
    ("UI",  "UI · 表现层（壳与前端工程）— 跨层",
     "[chat-as-os](../docs/PRD-v2-Agent/story-01-chat-as-os.md)", "M1–M3"),
    ("L4",  "L4 · 多视角推理 Multi-Lens — Story 4", "[multi-lens](../docs/PRD-v2-Agent/story-04-multi-lens.md)", "M2"),
    # ECO 置于 L4 之后：其分享物本体只取到 L4（`.stlens`），不依赖 L5/L6，
    # 且 09 自定位「跨层（L1 生态面）」——按层表置末会把它无据地压到全盘最后（见 决策日志 D-044）。
    ("ECO", "ECO · 生态与分享 — Story 10", "[skill-sharing](../docs/PRD-v2-Agent/story-10-skill-sharing.md)", "M4 · P1"),
    ("L5",  "L5 · 主动触达 Ambient Delivery — Story 7", "[ambient](../docs/PRD-v2-Agent/story-07-ambient-delivery.md)", "M3 · P1"),
    ("L6",  "L6 · 反思演进 Reflection Loop — Story 9", "[reflection](../docs/PRD-v2-Agent/story-09-reflection-loop.md)", "M4 · P2"),
    ("INT", "INT · 里程碑集成关卡 — 端到端数据流", "[00-架构总览](../docs/技术架构-v2/00-架构总览.md)", "M0–M4"),
]
LAYER_ORDER = {c: i for i, (c, *_ ) in enumerate(LAYERS)}
LAYER_STORY_REL = {c: s for c, _t, s, _m in LAYERS}  # ../docs 版（账本用）
MILESTONES = [
    ("M0", "骨架打通", "平台契约 + L0 基座 + L1 能力池最小闭环"),
    ("M1", "首次可对话", "Chat 主入口打通到 L2 记忆读写"),
    ("M2", "决策可用（MVP）", "L4 多视角中性推理闭环"),
    ("M3", "主动服务", "L5 Ambient Delivery 投递闭环"),
    ("M4", "自演进与生态", "L6 反思演进 + 生态分享"),
]

def layer_of(tid): return ID_RE.match(tid).group(0).split("-")[1]
def rel_to_file(p): return p.replace("../docs/", "../../docs/")   # 文件在 tasks/，比账本多一层
def slugify(t): return re.sub(r"[ ·/（）()§.,，。+·\-—:：→&]", "", t)[:26]

def ready_sort_key(t):
    """就绪集排序（工作流「调度规则」§2）。

    priority → **里程碑集成关卡优先** → 架构层号升序 → id 字典序。
    关卡优先：其 depends_on 已覆盖本里程碑全部叶子，故 ready 时即该里程碑唯一收口阻塞项，
    再按层号后置只会推迟 archive 与全量验证（故 INT 虽在 LAYERS 置末，此处须先于层号取用）。
    """
    lay = layer_of(t["id"])
    return (t["priority"], 0 if lay == "INT" else 1, LAYER_ORDER.get(lay, 99), t["id"])

# ---------- frontmatter ----------
def read_fm(path):
    lines = open(path, encoding="utf-8").read().splitlines()
    if not lines or lines[0].strip() != "---":
        return None, ""
    fm, i = {}, 1
    while i < len(lines) and lines[i].strip() != "---":
        if ":" in lines[i]:
            k, v = lines[i].split(":", 1)
            v = v.strip()
            if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":  # 去成对引号
                v = v[1:-1]
            fm[k.strip()] = v
        i += 1
    return fm, "\n".join(lines[i+1:]).strip("\n")

def fm_list(fm, key):
    v = (fm.get(key, "") or "").strip()
    if not v or v in ("[]", "—", "-", "null"): return []
    return [x.strip() for x in v.strip("[]").split(",") if x.strip()]

def serialize(fm, body):
    """回写任务文件：已知字段按固定序 → 未知字段原序追加；空值字段保留。

    保真约定（2026-09-26）：派生父状态会重写任务文件，因此这里**不得丢字段**——
    工具不认识的自定义键、以及 `verify:` 这类空值键一律原样保留；仅改要改的值。
    """
    order = ["id","parent","title","story","arch","arch_link","priority","milestone",
             "depends_on","status","decisions","verify"]
    keys = [k for k in order if k in fm] + [k for k in fm if k not in order]
    out = ["---"]
    for k in keys:
        v = fm[k]
        if v == "":
            out.append(f"{k}:")                       # 空值保留（read_fm 解析为空串）
        elif k == "arch_link":
            out.append(f'{k}: "{v}"')
        else:
            out.append(f"{k}: {v}")
    out += ["---", "", body]
    return "\n".join(out).rstrip() + "\n"

def write_file(path, text):
    """写文本文件，**强制 LF**（2026-09-26）。

    Windows 文本模式默认把 ``\\n`` 翻成 ``\\r\\n``；本目录的写入口（bootstrap /
    派生父状态 / 账本渲染 / verify_docs --fix）若不锁定换行符，就会在盘上留下
    CRLF，与仓库其余 LF 文件不一致——此后任何编辑都会产生整文件 diff。
    """
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def scan(root):
    res = []
    for dp, subdirs, fs in os.walk(root):
        if os.path.abspath(dp) == os.path.abspath(TASKS):
            subdirs[:] = [d for d in subdirs if d != "done"]
        for fn in fs:
            if not fn.endswith(".md") or fn.startswith("_"): continue
            path = os.path.join(dp, fn)
            fm, _ = read_fm(path)
            if not fm or not fm.get("id"): continue
            par = (fm.get("parent", "") or "").strip()
            res.append(dict(
                id=fm["id"], title=fm.get("title",""), arch_link=fm.get("arch_link", fm["id"]),
                priority=fm.get("priority",""), milestone=fm.get("milestone",""),
                status=fm.get("status","todo"), depends_on=fm_list(fm,"depends_on"),
                parent=(par if par not in ("null","—","-") else ""),
                rel=os.path.relpath(path, PM).replace("\\","/"), path=path))
    return res

# ---------- bootstrap ----------
HAND_AUTHORED = {"T-SC-001"}   # 手工撰写，永远不覆盖

def bootstrap(force=False):
    created = skipped = 0
    for ln in open(LEDGER, encoding="utf-8").read().splitlines():
        if not ln.strip().startswith("|"): continue
        cells = [c.strip() for c in ln.strip().strip("|").split("|")]
        if len(cells) < 7: continue
        m = ID_RE.search(cells[0])
        if not m: continue
        tid = m.group(0)
        lay = layer_of(tid)
        existing = next((f for f in os.listdir(TASKS) if f.startswith(tid + "-") and f.endswith(".md")
                         and os.path.isfile(os.path.join(TASKS, f))), None)
        if tid in HAND_AUTHORED:
            skipped += 1; continue
        if existing and not force and MARK not in open(os.path.join(TASKS, existing), encoding="utf-8").read():
            skipped += 1; continue                      # 保护无标记的手写文件
        title, prio, ms, depc, arch = cells[1], cells[2], cells[3], cells[4], cells[6]
        deps = [] if depc in ("—","-","") else ID_RE.findall(depc)
        story_links = LAYER_STORY_REL.get(lay, "")
        story_target = LINK_TGT.search(story_links).group(1) if LINK_TGT.search(story_links) else ""
        arch_file = rel_to_file(arch)                      # ../../docs 形式（文件内可用）
        body = (f"# {tid} · {title}\n\n{MARK}\n\n"
                f"## 目标\n{title}（开工 ④ 意图对齐时据 Story 补全）\n\n"
                f"## 验收标准（Given-When-Then，从 Story 抄）\n- 待 ④ 对齐时从对应 Story 验收段逐条补全\n\n"
                f"## 接口面\n- 暂无（④ 对齐时补：**输入**＝消费的前置接口（上游任务 id + 具体 API/落盘位置）；**输出**＝本任务交付的公共 API 与落盘位置）\n\n"
                f"## 假设与前提\n- 暂无（④ 对齐时补：A<n> 编号，每条含前提内容 / 若错的影响 / 验证方式；确认无假设写 `无（<原因>）`）\n\n"
                f"## 涉及契约\n{arch_file}\n\n"
                f"## 参考\n- Story（What）：{rel_to_file(story_links)}\n\n"
                f"## 备注\n实现细节不写此处，留给代码 / commit / 执行日志。\n")
        fm = {"id": tid, "title": title, "story": rel_to_file(story_target),
              "arch_link": arch_file,
              "priority": prio, "milestone": ms,
              "depends_on": "[" + ", ".join(deps) + "]" if deps else "[]",
              "status": "todo", "decisions": "[]", "verify": ""}
        fn = existing or f"{tid}-{slugify(title)}.md"
        write_file(os.path.join(TASKS, fn), serialize(fm, body))
        created += 1
    print(f"bootstrap: wrote {created}, protected(hand) {skipped}")

# ---------- 派生 + 就绪 ----------
def subtree_ids(pid, children):
    """``pid`` 的全部后代 id（不含 ``pid`` 自身）。"""
    out, stack = set(), [pid]
    while stack:
        for k in children.get(stack.pop(), []):
            if k["id"] not in out:
                out.add(k["id"]); stack.append(k["id"])
    return out

def derive_parent_deps(pid, children):
    """父 ``depends_on`` ＝直接 children 的 ``depends_on`` 并集，剔掉指向父自身子树（**含父 id 自身**）的边。

    剔子树边：子依赖兄弟 / 依赖父本身属子树内部次序，不构成父的**外部**前置；父 id 自身
    必须一并剔——``T-L0-005`` 的唯一子依赖父自身，不剔会派生出自我依赖，被依赖图判环。
    顺序＝子 id 序 + 子内原序（确定性，供首次落盘与检查比对）。
    """
    blocked = subtree_ids(pid, children) | {pid}
    out = []
    for k in sorted(children.get(pid, []), key=lambda t: t["id"]):
        for d in k["depends_on"]:
            if d not in blocked and d not in out:
                out.append(d)
    return out

def compute_status(tasks):
    byid = {t["id"]: t for t in tasks}
    children = {}
    for t in tasks:
        if t["parent"]: children.setdefault(t["parent"], []).append(t)
    def derive(pid):
        kids = children.get(pid, [])
        if not kids: return byid[pid]["status"]
        sts = [derive(k["id"]) for k in kids]
        v = "done" if all(s=="done" for s in sts) else "blocked" if any(s=="blocked" for s in sts) \
            else "doing" if any(s=="doing" for s in sts) else "todo"
        t = byid[pid]
        # 归档＝冻结历史：只派生 status，不重算 depends_on（同 verify_docs 检查 5/6 的历史豁免口径）
        new_deps = None
        if not t["rel"].startswith("tasks/done/"):
            cur = t["depends_on"]; want = derive_parent_deps(pid, children)
            if set(cur) != set(want):          # 按**集合**比较：仅顺序差异不写盘，免无意义 churn
                new_deps = [d for d in cur if d in want] + [d for d in want if d not in cur]
        if v != t["status"] or new_deps is not None:
            t["status"] = v
            fm, body = read_fm(t["path"]); fm["status"] = v
            if new_deps is not None:
                t["depends_on"] = new_deps                # 内存副本同步：账本渲染读的是它
                fm["depends_on"] = "[" + ", ".join(new_deps) + "]" if new_deps else "[]"
            write_file(t["path"], serialize(fm, body))
        return v
    for pid in list(children):
        if pid in byid: derive(pid)
    done_ids = {t["id"] for t in tasks if t["status"] == "done"}
    parents = {t["parent"] for t in tasks if t["parent"]}
    active = [t for t in tasks if not t["rel"].startswith("tasks/done/")]
    ready = [t for t in active if t["status"] == "todo" and t["id"] not in parents
             and all(d in done_ids for d in t["depends_on"])]
    return ready

# ---------- render ----------
def build_ledger():
    active = scan(TASKS); archived = scan(DONE); all_t = active + archived
    ready = compute_status(all_t)
    L = ["---","title: 任务账本","type: ledger","consumed_by: [编码 Agent, 项目负责人]",
         "note: 派生视图·勿手改，真相源在 tasks/*.md；跑 render_ledger.py render 重生成","---","",
         "# 任务账本","",
         "> ⚙️ **本文件由 `tools/render_ledger.py render` 自动生成，请勿手改；改任务只改 `tasks/T-*.md` 再 render。**",
         f"> 真相源 = `tasks/*.md` frontmatter。刷新 {datetime.now(CST):%Y-%m-%d %H:%M} · 活跃 {len(active)} / 已归档 {len(archived)}。",
         "> 生成 `... render` · 满里程碑归档 `... archive` · 派生父状态/依赖+就绪集 `... status`","",
         "## 里程碑视图","","| 里程碑 | 目标 | 覆盖层 | 完成 |","|---|---|---|---|"]
    for mid, name, goal in MILESTONES:
        tms = [t for t in all_t if t["milestone"] == mid]
        done = sum(1 for t in tms if t["status"] == "done")
        lset = sorted({layer_of(t["id"]) for t in tms}, key=lambda c: LAYER_ORDER.get(c,99))
        rng = (f"{lset[0]}–{lset[-1]}" if len(lset) > 1 else (lset[0] if lset else "—"))
        mark = "✅ " if tms and done == len(tms) else ""
        L.append(f"| {mid} · {name} | {goal} | {rng} | {mark}{done}/{len(tms)} |")
    L += ["", "## 依赖主轴（自底向上实现顺序）","",
          "`01 契约 → L0 → L1 → L2 → L3 → UI → L4 → ECO →（并行 L5）→ L6`；跨层一律经 `01-平台共享契约`，仅向下依赖。","",
          "## 就绪集（可开工 · todo 且依赖全 done）",""]
    if ready:
        for t in sorted(ready, key=ready_sort_key):
            L.append(f"- [`{t['id']}`]({t['rel']}) · {t['title']}（{t['priority']} / {t['milestone']}）")
    else: L.append("- （空）")
    L += ["","---",""]
    for code, head, story, mtag in LAYERS:
        rows = sorted([t for t in active if layer_of(t["id"]) == code], key=lambda x:x["id"])
        if not rows: continue
        L += [f"## {head}（{story}）｜{mtag}","",
              "| id | title | P | milestone | depends_on | status | arch |","|---|---|---|---|---|---|---|"]
        for t in rows:
            archcell = t["arch_link"].replace("../../docs/", "../docs/")   # 账本在 项目管理/ 层
            L.append(f"| [`{t['id']}`]({t['rel']}) | {t['title']} | {t['priority']} | {t['milestone']} | "
                     f"{', '.join(t['depends_on']) or '—'} | {t['status']} | {archcell} |")
        L.append("")
    if archived:
        L += ["## 已归档（里程碑完成）",""]
        for mid,*_ in MILESTONES:
            ids = sorted(t["id"] for t in archived if t["milestone"] == mid)
            if ids: L.append(f"- **{mid}** ✅ {len(ids)} 个 → `tasks/done/{mid}/`：{', '.join(ids)}")
        L.append("")
    text = "\n".join(L).rstrip() + "\n"
    return text, len(active), len(archived), len(ready)

def render():
    text, na, nr, nready = build_ledger()
    write_file(LEDGER, text)
    print(f"render: active {na}, archived {nr}, ready {nready} → 任务账本.md")

# ---------- archive ----------
def _norm(p): return os.path.normpath(p).replace("\\", "/")

def _link_path(raw):
    """``](raw)`` 的**路径**部分；非相对链接（锚点 / 协议 / 绝对路径）→ ``None``。

    与 ``verify_docs.link_target`` 同口径（去引号与 ``<>``、切掉 ``#``/``?`` 片段），
    这样「改写」与「校验」看的是同一批链接。
    """
    t = raw.strip().strip('"')
    if not t or t.startswith(NON_REL_PREFIX): return None
    t = t.split()[0].strip('<>').strip('"\'').split('#', 1)[0].split('?', 1)[0].strip()
    if not t or t.startswith(('/', '\\\\')): return None
    return t

def _retarget(text, here, candidates):
    """把 ``](target)`` 重定向到**首个存在**的候选路径（相对 ``here`` 输出）。

    :param here: 本文件所在目录（绝对）
    :param candidates: ``path -> [绝对路径, ...]``；按序取首个 ``exists`` 的。
        全部不存在 → 原样保留（留给 ``verify_docs`` 报断链，不静默猜）。

    三条约定：① 围栏代码段不动（同 ``verify_docs.strip_code`` 的范围）；
    ② 目标按原链接**仍可解析**时不动（幂等，重跑安全）；③ 只改 ``](...)`` 里的
    路径，正文其余部分逐字节不变。
    """
    def fix_seg(seg):
        def sub(m):
            head, raw, tail = m.group(1), m.group(2), m.group(3)
            p = _link_path(raw)
            if p is None: return m.group(0)
            for full in candidates(p):
                if os.path.exists(full):
                    rel = _norm(os.path.relpath(full, here))
                    if rel == _norm(p): return m.group(0)       # 仍成立 → 不动
                    frag = "#" + raw.split("#", 1)[1] if "#" in raw else ""
                    return f"{head}{rel}{frag}{tail}"
            return m.group(0)
        return MD_LINK.sub(sub, seg)
    return "".join(seg if i % 2 else fix_seg(seg) for i, seg in enumerate(FENCE.split(text)))

def _md_files():
    """仓库内全部 ``.md``（跳过 ``.git`` / 缓存 / 临时草稿目录，同断链扫描口径）。"""
    for dp, ds, fs in os.walk(ROOT):
        ds[:] = [d for d in ds if d not in SKIP_DIRS]
        for fn in sorted(fs):
            if fn.endswith(".md"):
                yield os.path.join(dp, fn)

def _rewrite_after_move(mid, moved):
    """移动后改正受影响链接（``archive`` 的第二步；只此一处做链接改写）。

    - **批内文件**：链接要么指向「同批一起搬走的邻居」（现为同目录），要么指向
      「没搬走的文件」（只多深了两层）。两种都由候选表按存在性判定，不靠数 ``../``。
    - **其余文件**：只改那些确实落在本批文件上的链接（指向别处的分毫不动）。
    """
    new_paths = {os.path.abspath(n) for _o, n in moved}
    dest = os.path.join(DONE, mid)

    def fix(full, cands):
        text = open(full, encoding="utf-8").read()
        fixed = _retarget(text, os.path.dirname(full), cands)
        if fixed != text: write_file(full, fixed)

    for _old, new in moved:                      # ① 批内文件自身
        here = os.path.dirname(new)
        fix(new, lambda p, here=here: [
            os.path.join(here, p),                                    # 仍成立（幂等）
            os.path.join(here, os.path.basename(p.rstrip("/"))),      # 同批一起搬走
            os.path.join(TASKS, p),                                   # 只是深了两层
        ])
    for full in _md_files():                     # ② 全仓其余 .md
        if os.path.abspath(full) in new_paths: continue
        if os.path.abspath(full) == os.path.abspath(LEDGER): continue  # 派生视图，render 重生
        here = os.path.dirname(full)
        fix(full, lambda p, here=here: [
            os.path.join(here, p),                                    # 仍成立（幂等）
            os.path.join(dest, os.path.basename(p.rstrip("/"))),      # 目标搬进了本批
        ])

def archive(dry):
    compute_status(scan(TASKS) + scan(DONE))
    for mid, *_ in MILESTONES:
        tms = [t for t in scan(TASKS) if t["milestone"] == mid]
        if tms and all(t["status"] == "done" for t in tms):
            print(f"{'DRY ' if dry else ''}archive {mid}: {len(tms)} → tasks/done/{mid}/")
            if dry: continue
            os.makedirs(os.path.join(DONE, mid), exist_ok=True)
            moved = [(t["path"], os.path.join(DONE, mid, os.path.basename(t["path"])))
                     for t in tms]
            for old, new in moved:
                shutil.move(old, new)
            _rewrite_after_move(mid, moved)
            render()                             # 账本随移动重生，收工时不必再跑 render

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["bootstrap","render","archive","status"])
    ap.add_argument("--dry", action="store_true"); ap.add_argument("--force", action="store_true")
    a = ap.parse_args()
    if a.cmd == "bootstrap": bootstrap(force=a.force)
    elif a.cmd == "render": render()
    elif a.cmd == "archive": archive(a.dry)
    else: print("ready:", [t["id"] for t in compute_status(scan(TASKS)+scan(DONE))])

if __name__ == "__main__": main()
