#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""render_ledger.py — ST Agent 任务账本生成器

tasks/*.md 的 YAML frontmatter 是唯一真相源；任务账本.md 是派生视图，勿手改。

子命令：
  bootstrap   一次性：把（手写的）现有账本表格里的行导入为 tasks/T-*.md
              仅创建缺失或带 AUTO 标记的文件；手写文件（无标记）不受影响
  render      扫描 tasks/ 与 tasks/done/ → 重新生成 项目管理/任务账本.md
  archive     把「全部任务 done」的里程碑整批移入 tasks/done/<Mn>/（--dry 预览）
  status      按 children 重算父任务 status；打印就绪集

frontmatter 约定：
  文件内部链接（story / arch / 正文）相对 tasks/ → 用 ../../docs/
  arch_link 字段专供账本渲染，相对 项目管理/ → 用 ../docs/
"""
import os, re, shutil, argparse
from datetime import datetime, timezone, timedelta

HERE = os.path.dirname(os.path.abspath(__file__))
PM   = os.path.dirname(HERE)
TASKS= os.path.join(PM, "tasks")
DONE = os.path.join(TASKS, "done")
LEDGER = os.path.join(PM, "任务账本.md")
MARK = "<!-- auto-generated by render_ledger bootstrap -->"

ID_RE = re.compile(r"T-(?:SC|L\d|ECO|INT)-\d{3}")
LINK_TGT = re.compile(r'\]\(([^)]+)\)')
CST = timezone(timedelta(hours=8))

LAYERS = [
    ("SC",  "SC · 平台共享契约 — Story 平台通用能力",
     "[`10-platform-capabilities`](../docs/PRD-v2-Agent/10-platform-capabilities.md)", "M0"),
    ("L0",  "L0 · 本地优先基座 — Story 5", "[local-first](../docs/PRD-v2-Agent/story-05-local-first.md)", "M0"),
    ("L1",  "L1 · 能力底座 Skills/MCP — Story 2 / 6 / 8",
     "[runtime](../docs/PRD-v2-Agent/story-02-skills-runtime.md) / [studio](../docs/PRD-v2-Agent/story-06-skill-studio.md) / [mcp](../docs/PRD-v2-Agent/story-08-mcp-hub.md)", "M0"),
    ("L2",  "L2 · 记忆图谱 — Story 3", "[memory-graph](../docs/PRD-v2-Agent/story-03-memory-graph.md)", "M1"),
    ("L3",  "L3 · 对话主入口 Chat-as-OS — Story 1", "[chat-as-os](../docs/PRD-v2-Agent/story-01-chat-as-os.md)", "M1"),
    ("L4",  "L4 · 多视角推理 Multi-Lens — Story 4", "[multi-lens](../docs/PRD-v2-Agent/story-04-multi-lens.md)", "M2"),
    ("L5",  "L5 · 主动触达 Ambient Delivery — Story 7", "[ambient](../docs/PRD-v2-Agent/story-07-ambient-delivery.md)", "M3 · P1"),
    ("L6",  "L6 · 反思演进 Reflection Loop — Story 9", "[reflection](../docs/PRD-v2-Agent/story-09-reflection-loop.md)", "M4 · P2"),
    ("ECO", "ECO · 生态与分享 — Story 10", "[skill-sharing](../docs/PRD-v2-Agent/story-10-skill-sharing.md)", "M4 · P2"),
    ("INT", "INT · 里程碑集成关卡 — 端到端数据流", "[00-架构总览](../docs/技术架构-v2/00-架构总览.md)", "M0–M4"),
]
LAYER_ORDER = {c: i for i, (c, *_ ) in enumerate(LAYERS)}
LAYER_STORY_REL = {c: s for c, _t, s, _m in LAYERS}  # ../docs 版（账本用）
MILESTONES = [
    ("M0", "骨架打通", "平台契约 + L0 基座 + L1 能力池最小闭环"),
    ("M1", "首次可对话", "Chat 主入口打通到 L2 记忆读写"),
    ("M2", "决策可用（MVP）", "L4 多视角中性推理闭环"),
    ("M3", "主动服务", "L5 Ambient Delivery 投递闭环"),
    ("M4", "自演进与生态", "L6 反思演进 + 生态分享"),
]

def layer_of(tid): return ID_RE.match(tid).group(0).split("-")[1]
def rel_to_file(p): return p.replace("../docs/", "../../docs/")   # 文件在 tasks/，比账本多一层
def slugify(t): return re.sub(r"[ ·/（）()§.,，。+·\-—:：→&]", "", t)[:26]

# ---------- frontmatter ----------
def read_fm(path):
    lines = open(path, encoding="utf-8").read().splitlines()
    if not lines or lines[0].strip() != "---":
        return None, ""
    fm, i = {}, 1
    while i < len(lines) and lines[i].strip() != "---":
        if ":" in lines[i]:
            k, v = lines[i].split(":", 1)
            v = v.strip()
            if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":  # 去成对引号
                v = v[1:-1]
            fm[k.strip()] = v
        i += 1
    return fm, "\n".join(lines[i+1:]).strip("\n")

def fm_list(fm, key):
    v = (fm.get(key, "") or "").strip()
    if not v or v in ("[]", "—", "-", "null"): return []
    return [x.strip() for x in v.strip("[]").split(",") if x.strip()]

def serialize(fm, body):
    """回写任务文件：已知字段按固定序 → 未知字段原序追加；空值字段保留。

    保真约定（2026-09-26）：派生父状态会重写任务文件，因此这里**不得丢字段**——
    工具不认识的自定义键、以及 `verify:` 这类空值键一律原样保留；仅改要改的值。
    """
    order = ["id","parent","title","story","arch","arch_link","priority","milestone",
             "depends_on","status","decisions","verify"]
    keys = [k for k in order if k in fm] + [k for k in fm if k not in order]
    out = ["---"]
    for k in keys:
        v = fm[k]
        if v == "":
            out.append(f"{k}:")                       # 空值保留（read_fm 解析为空串）
        elif k == "arch_link":
            out.append(f'{k}: "{v}"')
        else:
            out.append(f"{k}: {v}")
    out += ["---", "", body]
    return "\n".join(out).rstrip() + "\n"

def write_file(path, text):
    """写文本文件，**强制 LF**（2026-09-26）。

    Windows 文本模式默认把 ``\\n`` 翻成 ``\\r\\n``；本目录的写入口（bootstrap /
    派生父状态 / 账本渲染 / verify_docs --fix）若不锁定换行符，就会在盘上留下
    CRLF，与仓库其余 LF 文件不一致——此后任何编辑都会产生整文件 diff。
    """
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def scan(root):
    res = []
    for dp, subdirs, fs in os.walk(root):
        if os.path.abspath(dp) == os.path.abspath(TASKS):
            subdirs[:] = [d for d in subdirs if d != "done"]
        for fn in fs:
            if not fn.endswith(".md") or fn.startswith("_"): continue
            path = os.path.join(dp, fn)
            fm, _ = read_fm(path)
            if not fm or not fm.get("id"): continue
            par = (fm.get("parent", "") or "").strip()
            res.append(dict(
                id=fm["id"], title=fm.get("title",""), arch_link=fm.get("arch_link", fm["id"]),
                priority=fm.get("priority",""), milestone=fm.get("milestone",""),
                status=fm.get("status","todo"), depends_on=fm_list(fm,"depends_on"),
                parent=(par if par not in ("null","—","-") else ""),
                rel=os.path.relpath(path, PM).replace("\\","/"), path=path))
    return res

# ---------- bootstrap ----------
HAND_AUTHORED = {"T-SC-001"}   # 手工撰写，永远不覆盖

def bootstrap(force=False):
    created = skipped = 0
    for ln in open(LEDGER, encoding="utf-8").read().splitlines():
        if not ln.strip().startswith("|"): continue
        cells = [c.strip() for c in ln.strip().strip("|").split("|")]
        if len(cells) < 7: continue
        m = ID_RE.search(cells[0])
        if not m: continue
        tid = m.group(0)
        lay = layer_of(tid)
        existing = next((f for f in os.listdir(TASKS) if f.startswith(tid + "-") and f.endswith(".md")
                         and os.path.isfile(os.path.join(TASKS, f))), None)
        if tid in HAND_AUTHORED:
            skipped += 1; continue
        if existing and not force and MARK not in open(os.path.join(TASKS, existing), encoding="utf-8").read():
            skipped += 1; continue                      # 保护无标记的手写文件
        title, prio, ms, depc, arch = cells[1], cells[2], cells[3], cells[4], cells[6]
        deps = [] if depc in ("—","-","") else ID_RE.findall(depc)
        story_links = LAYER_STORY_REL.get(lay, "")
        story_target = LINK_TGT.search(story_links).group(1) if LINK_TGT.search(story_links) else ""
        arch_file = rel_to_file(arch)                      # ../../docs 形式（文件内可用）
        body = (f"# {tid} · {title}\n\n{MARK}\n\n"
                f"## 目标\n{title}（开工 ④ 意图对齐时据 Story 补全）\n\n"
                f"## 验收标准（Given-When-Then，从 Story 抄）\n- 待 ④ 对齐时从对应 Story 验收段逐条补全\n\n"
                f"## 接口面\n- 暂无（④ 对齐时补：**输入**＝消费的前置接口（上游任务 id + 具体 API/落盘位置）；**输出**＝本任务交付的公共 API 与落盘位置）\n\n"
                f"## 假设与前提\n- 暂无（④ 对齐时补：A<n> 编号，每条含前提内容 / 若错的影响 / 验证方式；确认无假设写 `无（<原因>）`）\n\n"
                f"## 涉及契约\n{arch_file}\n\n"
                f"## 参考\n- Story（What）：{rel_to_file(story_links)}\n\n"
                f"## 备注\n实现细节不写此处，留给代码 / commit / 执行日志。\n")
        fm = {"id": tid, "title": title, "story": rel_to_file(story_target),
              "arch_link": arch_file,
              "priority": prio, "milestone": ms,
              "depends_on": "[" + ", ".join(deps) + "]" if deps else "[]",
              "status": "todo", "decisions": "[]", "verify": ""}
        fn = existing or f"{tid}-{slugify(title)}.md"
        write_file(os.path.join(TASKS, fn), serialize(fm, body))
        created += 1
    print(f"bootstrap: wrote {created}, protected(hand) {skipped}")

# ---------- 派生 + 就绪 ----------
def compute_status(tasks):
    byid = {t["id"]: t for t in tasks}
    children = {}
    for t in tasks:
        if t["parent"]: children.setdefault(t["parent"], []).append(t)
    def derive(pid):
        kids = children.get(pid, [])
        if not kids: return byid[pid]["status"]
        sts = [derive(k["id"]) for k in kids]
        v = "done" if all(s=="done" for s in sts) else "blocked" if any(s=="blocked" for s in sts) \
            else "doing" if any(s=="doing" for s in sts) else "todo"
        if v != byid[pid]["status"]:
            byid[pid]["status"] = v
            fm, body = read_fm(byid[pid]["path"]); fm["status"] = v
            write_file(byid[pid]["path"], serialize(fm, body))
        return v
    for pid in list(children):
        if pid in byid: derive(pid)
    done_ids = {t["id"] for t in tasks if t["status"] == "done"}
    parents = {t["parent"] for t in tasks if t["parent"]}
    active = [t for t in tasks if not t["rel"].startswith("tasks/done/")]
    ready = [t for t in active if t["status"] == "todo" and t["id"] not in parents
             and all(d in done_ids for d in t["depends_on"])]
    return ready

# ---------- render ----------
def build_ledger():
    active = scan(TASKS); archived = scan(DONE); all_t = active + archived
    ready = compute_status(all_t)
    L = ["---","title: 任务账本","type: ledger","consumed_by: [编码 Agent, 项目负责人]",
         "note: 派生视图·勿手改，真相源在 tasks/*.md；跑 render_ledger.py render 重生成","---","",
         "# 任务账本","",
         "> ⚙️ **本文件由 `tools/render_ledger.py render` 自动生成，请勿手改；改任务只改 `tasks/T-*.md` 再 render。**",
         f"> 真相源 = `tasks/*.md` frontmatter。刷新 {datetime.now(CST):%Y-%m-%d %H:%M} · 活跃 {len(active)} / 已归档 {len(archived)}。",
         "> 生成 `... render` · 满里程碑归档 `... archive` · 派生父状态+就绪集 `... status`","",
         "## 里程碑视图","","| 里程碑 | 目标 | 覆盖层 | 完成 |","|---|---|---|---|"]
    for mid, name, goal in MILESTONES:
        tms = [t for t in all_t if t["milestone"] == mid]
        done = sum(1 for t in tms if t["status"] == "done")
        lset = sorted({layer_of(t["id"]) for t in tms}, key=lambda c: LAYER_ORDER.get(c,99))
        rng = (f"{lset[0]}–{lset[-1]}" if len(lset) > 1 else (lset[0] if lset else "—"))
        mark = "✅ " if tms and done == len(tms) else ""
        L.append(f"| {mid} · {name} | {goal} | {rng} | {mark}{done}/{len(tms)} |")
    L += ["", "## 依赖主轴（自底向上实现顺序）","",
          "`01 契约 → L0 → L1 → L2 → L3 → L4 →（并行 L5）→ L6 → ECO`；跨层一律经 `01-平台共享契约`，仅向下依赖。","",
          "## 就绪集（可开工 · todo 且依赖全 done）",""]
    if ready:
        for t in sorted(ready, key=lambda x:(x["priority"], LAYER_ORDER.get(layer_of(x["id"]),99), x["id"])):
            L.append(f"- [`{t['id']}`]({t['rel']}) · {t['title']}（{t['priority']} / {t['milestone']}）")
    else: L.append("- （空）")
    L += ["","---",""]
    for code, head, story, mtag in LAYERS:
        rows = sorted([t for t in active if layer_of(t["id"]) == code], key=lambda x:x["id"])
        if not rows: continue
        L += [f"## {head}（{story}）｜{mtag}","",
              "| id | title | P | milestone | depends_on | status | arch |","|---|---|---|---|---|---|---|"]
        for t in rows:
            archcell = t["arch_link"].replace("../../docs/", "../docs/")   # 账本在 项目管理/ 层
            L.append(f"| [`{t['id']}`]({t['rel']}) | {t['title']} | {t['priority']} | {t['milestone']} | "
                     f"{', '.join(t['depends_on']) or '—'} | {t['status']} | {archcell} |")
        L.append("")
    if archived:
        L += ["## 已归档（里程碑完成）",""]
        for mid,*_ in MILESTONES:
            ids = sorted(t["id"] for t in archived if t["milestone"] == mid)
            if ids: L.append(f"- **{mid}** ✅ {len(ids)} 个 → `tasks/done/{mid}/`：{', '.join(ids)}")
        L.append("")
    text = "\n".join(L).rstrip() + "\n"
    return text, len(active), len(archived), len(ready)

def render():
    text, na, nr, nready = build_ledger()
    write_file(LEDGER, text)
    print(f"render: active {na}, archived {nr}, ready {nready} → 任务账本.md")

# ---------- archive ----------
def archive(dry):
    compute_status(scan(TASKS) + scan(DONE))
    for mid, *_ in MILESTONES:
        tms = [t for t in scan(TASKS) if t["milestone"] == mid]
        if tms and all(t["status"] == "done" for t in tms):
            print(f"{'DRY ' if dry else ''}archive {mid}: {len(tms)} → tasks/done/{mid}/")
            if not dry:
                os.makedirs(os.path.join(DONE, mid), exist_ok=True)
                for t in tms: shutil.move(t["path"], os.path.join(DONE, mid, os.path.basename(t["path"])))

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["bootstrap","render","archive","status"])
    ap.add_argument("--dry", action="store_true"); ap.add_argument("--force", action="store_true")
    a = ap.parse_args()
    if a.cmd == "bootstrap": bootstrap(force=a.force)
    elif a.cmd == "render": render()
    elif a.cmd == "archive": archive(a.dry)
    else: print("ready:", [t["id"] for t in compute_status(scan(TASKS)+scan(DONE))])

if __name__ == "__main__": main()
